review_model = "gpt-5.5"
model = "gpt-5.5"
model_reasoning_effort = "high"
plan_mode_reasoning_effort = "xhigh"
model_auto_compact_token_limit = 200000
model_provider = "codex-lb"
personality = "pragmatic"
service_tier = "fast"
hide_agent_reasoning = true
show_raw_agent_reasoning = false
commit_attribution = ""
sandbox_mode = "workspace-write"
approval_policy = "untrusted"

notify = ["/usr/bin/afplay", "/System/Library/Sounds/Submarine.aiff"]

[sandbox_workspace_write]
network_access = true

[model_providers.codex-lb]
name = "OpenAI"
base_url = "http://codexlb00.usce1.mgmt.internal.amplemarket.com:2455/backend-api/codex"
wire_api = "responses"
supports_websockets = true
requires_openai_auth = true

[mcp_servers.grafana]
url = "https://grafana-mcp.gke00.usce1.mgmt.internal.amplemarket.com/mcp"

[mcp_servers.pganalyze]
url = "https://pganalyze-mcp.gke00.usce1.mgmt.internal.amplemarket.com/mcp"


[analytics]
enabled = false

[memories]
generate_memories = false
use_memories = false

[features]
js_repl = false
memories = false
chronicle = false

[desktop]
followUpQueueMode = "queue"
mac-menu-bar-enabled = false
preventSleepWhileRunning = true
notifications-turn-mode = "always"
usePointerCursors = false
codeFontSize = 17
sansFontSize = 14
appearanceDiffMarkerStyle = "color"
useFontSmoothing = true
dock-icon-preference = "app-default"
appearanceLightCodeThemeId = "codex"
appshotSoundEnabled = true
git-pull-request-merge-method = "squash"
git-create-pull-request-as-draft = true

[desktop.appearanceLightChromeTheme]
accent = "#0169cc"
contrast = 45
ink = "#0d0d0d"
opaqueWindows = false
surface = "#ffffff"

[desktop.appearanceLightChromeTheme.fonts]
code = "JetBrains Mono NL"

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#00a240"
diffRemoved = "#e02e2a"
skill = "#751ed9"
