[theme-colors]
bg-color = "white"
border-color = "darkgray"
text-color = "black"
tab-text-color = "blue"
hops-table-header-bg-color = "gray"
hops-table-header-text-color = "black"
hops-table-row-active-text-color = "black"
hops-table-row-inactive-text-color = "darkgray"
hops-chart-selected-color = "blue"
hops-chart-unselected-color = "darkgray"
hops-chart-axis-color = "gray"
frequency-chart-bar-color = "blue"
frequency-chart-text-color = "white"
flows-chart-bar-selected-color = "blue"
flows-chart-bar-unselected-color = "gray"
flows-chart-text-current-color = "white"
flows-chart-text-non-current-color = "black"
samples-chart-color = "darkgoldenrod"
samples-chart-lost-color = "red"
help-dialog-bg-color = "white"
help-dialog-text-color = "black"
settings-dialog-bg-color = "white"
settings-tab-text-color = "blue"
settings-table-header-text-color = "black"
settings-table-header-bg-color = "gray"
settings-table-row-text-color = "black"
map-world-color = "black"
map-radius-color = "darkgoldenrod"
map-selected-color = "blue"
map-info-panel-border-color = "darkgray"
map-info-panel-bg-color = "white"
map-info-panel-text-color = "black"
info-bar-bg-color = "gray"
info-bar-text-color = "black"
