import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const messages = [
  // Short
  "Abracadabraing...",
  "Absconding...",
  "Absquatulating...",
  "Alakazaming...",
  "Algebraic-data-typing...",
  "Amalgamating...",
  "Ambling...",
  "Angling...",
  "Appling...",
  "Balderdashing...",
  "Ballyhooing...",
  "Bamboozling...",
  "Battering...",
  "Bedazzling...",
  "Bedoodling...",
  "Befuddling...",
  "Beguiling...",
  "Bespangling...",
  "Beta-reducing...",
  "Bewitching...",
  "Biffing...",
  "Bindifying...",
  "Blathering...",
  "Blithering...",
  "Blorping...",
  "Bodge-jobbing...",
  "Boffing...",
  "Bonking...",
  "Bouldering...",
  "Brewing...",
  "Brimming...",
  "Brouhahaing...",
  "Bubbling...",
  "Bumbling...",
  "Bungling...",
  "Burbling...",
  "Bustling...",
  "Canoodling...",
  "Catamorphing...",
  "Cattywampusing...",
  "Channelling...",
  "Chattering...",
  "Church-encoding...",
  "Clamoring...",
  "Clanking...",
  "Clattering...",
  "Clomping...",
  "Clunking...",
  "Codswalloping...",
  "Cogitating...",
  "Combobulating...",
  "Composing...",
  "Concocting...",
  "Confabulating...",
  "Contemplating...",
  "Contraptioning...",
  "Coruscating...",
  "Crumbling...",
  "Currying...",
  "Dangling...",
  "Dawdling...",
  "Daydreaming...",
  "Defenestrating...",
  "Destructuring...",
  "Dillydallying...",
  "Discombobulating...",
  "Dithering...",
  "Doing...",
  "Doodling...",
  "Doohickeying...",
  "Drumming...",
  "Effect-tracking...",
  "Effervescing...",
  "Enamoring...",
  "Enchanting...",
  "Eta-reducing...",
  "Extemporizing...",
  "Faffing...",
  "Feathering...",
  "Fermenting...",
  "Fiddledeedeeing...",
  "Fiddlefaddling...",
  "Fiddling...",
  "Figgling...",
  "Finagling...",
  "Fizzing...",
  "Flapdoodling...",
  "Flattering...",
  "Flibbertigibbeting...",
  "Flittering...",
  "Flonking...",
  "Flummoxing...",
  "Flumping...",
  "Folding...",
  "Foraging...",
  "Fossicking...",
  "Freestyling...",
  "Frittering...",
  "Frolicking...",
  "Fudging...",
  "Fumbling...",
  "Functoring...",
  "Futzing...",
  "Galumphing...",
  "Gamboling...",
  "Gestating...",
  "Gibbering...",
  "Gizmoing...",
  "Glamoring...",
  "Glimmering...",
  "Glittering...",
  "Glurping...",
  "Gobbledygooking...",
  "Gonkulating...",
  "Grooving...",
  "Grumbling...",
  "Gurgling...",
  "Hacky-sacking...",
  "Hammering...",
  "Hatching...",
  "Heathering...",
  "Higgledypiggledying...",
  "Higgling...",
  "Hindley-Milnering...",
  "Hocuspocusing...",
  "Hogwashing...",
  "Hokeypokeying...",
  "Honking...",
  "Hootenannying...",
  "Hornswoggling...",
  "Hullaballooing...",
  "Humbling...",
  "Humming...",
  "Hustling...",
  "Imagining...",
  "Immutabilizing...",
  "Improvising...",
  "Jabbering...",
  "Jamming...",
  "Jangling...",
  "Jiggerypokering...",
  "Jiggling...",
  "Jingling...",
  "Jittering...",
  "Jostling...",
  "Jumbling...",
  "Jungling...",
  "Juryrigging...",
  "Kerfuffling...",
  "Kerplunking...",
  "Kibbitzing...",
  "Kingling...",
  "Kleisliing...",
  "Kludging...",
  "Lambda-lifting...",
  "Lazifying...",
  "Leathering...",
  "Lollygagging...",
  "Luminescing...",
  "Lurking...",
  "Macgyvering...",
  "Malarkeying...",
  "Malingering...",
  "Mangling...",
  "Marinating...",
  "Mattering...",
  "Meandering...",
  "Memoizing...",
  "Mesmerizing...",
  "Miffing...",
  "Mingling...",
  "Moldering...",
  "Monadifying...",
  "Moseying...",
  "Mulligrubbing...",
  "Mulling...",
  "Mumbling...",
  "Mumbojumboing...",
  "Musing...",
  "Mystifying...",
  "Nambypambying...",
  "Nattering...",
  "Niggling...",
  "Noodging...",
  "Noodling...",
  "Numbing...",
  "Oscillating...",
  "Pattering...",
  "Pattern-matching...",
  "Perambulating...",
  "Percolating...",
  "Perplexing...",
  "Persnicketing...",
  "Phosphorescing...",
  "Piggling...",
  "Pirouetting...",
  "Pizzazzing...",
  "Plonking...",
  "Plumbing...",
  "Pointfreeing...",
  "Pondering...",
  "Pontificating...",
  "Poppycocking...",
  "Pottering...",
  "Primming...",
  "Procrastinating...",
  "Pulsating...",
  "Puttering...",
  "Rattling...",
  "Razzledazzling...",
  "Razzmatazzing...",
  "Recombobulating...",
  "Recursing...",
  "Referentially-transparenting...",
  "Ricocheting...",
  "Rigmaroling...",
  "Ringling...",
  "Rube-goldberging...",
  "Rumbling...",
  "Ruminating...",
  "Rummaging...",
  "Rustling...",
  "Sashaying...",
  "Sauntering...",
  "Scampering...",
  "Scattering...",
  "Scavenging...",
  "Schlepping...",
  "Schlurping...",
  "Schmalzing...",
  "Schmoozing...",
  "Scintillating...",
  "Scribbling...",
  "Shattering...",
  "Shenaniganing...",
  "Shimmering...",
  "Shimmying...",
  "Shindigging...",
  "Shouldering...",
  "Simmering...",
  "Singling...",
  "Skedaddling...",
  "Skedoodling...",
  "Skimming...",
  "Skittering...",
  "Skulking...",
  "Skullduggering...",
  "Sleuthing...",
  "Slithering...",
  "Smoldering...",
  "Snazzifying...",
  "Snollygosting...",
  "Snorkeling...",
  "Snurfling...",
  "Somersaulting...",
  "Sparkling...",
  "Spelunking...",
  "Splattering...",
  "Splooshing...",
  "Splorfing...",
  "Splunging...",
  "Squelching...",
  "Squiggling...",
  "Squonking...",
  "Stammering...",
  "Steeping...",
  "Strangling...",
  "Struggling...",
  "Strumming...",
  "Stumbling...",
  "Sublimating...",
  "Swashbuckling...",
  "Swooshing...",
  "Synthesizing...",
  "Tail-calling...",
  "Tangling...",
  "Taradiddling...",
  "Tattering...",
  "Teetering...",
  "Tethering...",
  "Thingamajigging...",
  "Thrumming...",
  "Thumbing...",
  "Thunking...",
  "Thwacking...",
  "Tingling...",
  "Tinkering...",
  "Tittering...",
  "Tokenmaxxing...",
  "Tomfoolering...",
  "Tottering...",
  "Traipsing...",
  "Transmuting...",
  "Traversing...",
  "Trimming...",
  "Tumbling...",
  "Twittering...",
  "Unbefuddling...",
  "Uncurrying...",
  "Undulating...",
  "Unfolding...",
  "Vamoosing...",
  "Vibing...",
  "Wangling...",
  "Weathering...",
  "Whatchamacalliting...",
  "Whimming...",
  "Whirring...",
  "Whomping...",
  "Whooshing...",
  "Wibbling...",
  "Widdershinning...",
  "Widgeting...",
  "Wiggling...",
  "Wingdinging...",
  "Wishywashing...",
  "Withering...",
  "Wobbling...",
  "Woolgathering...",
  "Wrangling...",
  "Wriggling...",
  "Y-combinating...",
  "Yammering...",
  "Yodeling...",
  "Zigzagging...",
  "Zippering...",
  "Zonking...",
  "Zorping...",

  // Long
  "Absolving the abstractions...",
  "Abyss staring back...",
  "Achieving enlightenment...",
  "Adding a dash of elegance...",
  "Adjusting the cosmic frequency...",
  "Aerating the arrays...",
  "Aging the algorithms gracefully...",
  "Aligning the chakras...",
  "Anointing the algorithms...",
  "Aping the Applicative for sequential delight...",
  "Apologizing to the type checker...",
  "Appeasing the garbage collector...",
  "Applying the Y combinator with great ceremony...",
  "Archeologically analyzing the architecture...",
  "Arranging flowers in the feature flags...",
  "Ascending to a higher plane...",
  "Asking DNS for directions...",
  "Asking the electrons...",
  "Asking the hamsters to run faster...",
  "Asking the monad what it wants to be when it grows up...",
  "Backpacking through the binaries...",
  "Baking at 350 kilobytes...",
  "Baptizing the binary...",
  "Barbecuing the bugs...",
  "Bargaining with fate...",
  "Believing really hard...",
  "Beta-reducing towards enlightenment...",
  "Bewitching the boolean logic...",
  "Binding through the Either of hope and despair...",
  "Blanching the branches...",
  "Blessing the build process...",
  "Bottling the buffers...",
  "Braiding the call stacks...",
  "Braising the breakpoints...",
  "Bribing the byte fairies...",
  "Bribing the compiler...",
  "Bribing the runtime...",
  "Building a tiny fort out of stack frames...",
  "Bungee jumping into the backend...",
  "Burning sage in the staging environment...",
  "Buttering up the firewall...",
  "Caffeinating...",
  "Calibrating the flux capacitor...",
  "Camping in the codebase...",
  "Canning the constants...",
  "Caramelizing the callbacks...",
  "Catamorphing the recursive structure into soup...",
  "Channeling the ancient developers...",
  "Charging the crystals...",
  "Charming the curly braces...",
  "Checking if the servers are still friends...",
  "Checking under the hood...",
  "Cherry-picking the commits...",
  "Church-encoding the integers for fun...",
  "Cleansing the closures...",
  "Communing with the machine spirit...",
  "Composing pure functions like a bouquet...",
  "Consecrating the callbacks...",
  "Consulting ancient scrolls...",
  "Consulting the oracle...",
  "Consulting the rubber duck...",
  "Consulting the void...",
  "Convincing the linter to chill...",
  "Convincing the pixels to cooperate...",
  "Counting the sheep in the thread pool...",
  "Cracking the conundrums...",
  "Crocheting a blanket for the bare metal...",
  "Cross-examining the debugger...",
  "Curing the code smells...",
  "Currying favor with the type system...",
  "Cursing the cache misses...",
  "Dancing with dependencies...",
  "Decanting the data structures...",
  "Decoding the mysteries...",
  "Decorating the deployment...",
  "Deforesting the intermediate lists...",
  "Destructuring the problem into named pieces...",
  "Discovering hidden semicolons...",
  "Divining the answer...",
  "Doing the deployment dance...",
  "Dowsing for bugs...",
  "Drizzling debug sauce...",
  "Dusting off the neurons...",
  "Dusting the forgotten TODOs...",
  "Emancipating the enums...",
  "Enchanting the error handlers...",
  "Encoding the business rules in the types...",
  "Eta-reducing the unnecessary ceremony...",
  "Excavating ancient APIs...",
  "Existentially questioning...",
  "Exorcising the exceptions...",
  "Experiencing a flash of insight...",
  "Feeding the machine...",
  "Feeding treats to well-behaved assertions...",
  "Filing a complaint with the event loop...",
  "Filtering out the impure thoughts...",
  "Flambéing the failures...",
  "Flattering the floating points...",
  "Flirting with the database...",
  "Fluffing the pillows of the happy path...",
  "Folding in the features...",
  "Folding the laundry of technical debt...",
  "Folding the list into a single beautiful thought...",
  "Forgiving the for loops...",
  "Fossil hunting in the functions...",
  "Freeing the functions...",
  "Frosting the functions...",
  "Fusing the maps to please the optimizer...",
  "Garnishing the getters...",
  "Gently unwrapping the Maybe...",
  "Giving the code a pep talk...",
  "Giving the mutex a pep talk...",
  "Glamping in the globals...",
  "Glazing the graphics...",
  "Greasing the gears...",
  "Grilling the glitches...",
  "Hang gliding through the heap...",
  "Hanging curtains on the public interface...",
  "Harvesting the outputs...",
  "Having a little think...",
  "Having a moment of clarity...",
  "Having words with the cache...",
  "Herding cats in memory...",
  "Herding pointers...",
  "Hexing the hexadecimals...",
  "Hiking through the headers...",
  "Holding a seance for deleted code...",
  "Hoping for the best...",
  "Hosting a mixer for microservices...",
  "Hosting a town hall for the tabs...",
  "Hypnotizing the hash tables...",
  "Icing the interfaces...",
  "Interrogating the stack trace...",
  "Introducing the frontend to the backend...",
  "Invoking elder functions...",
  "Ironing the wrinkled state...",
  "Jarring the JavaScript...",
  "Jinxing the JSON parsers...",
  "Kicking the tires...",
  "Kleisli-composing my way out of this mess...",
  "Kneading the namespaces...",
  "Knitting a cozy for the cold start...",
  "Lazily evaluating whether to care...",
  "Leaving a voicemail for the monolith...",
  "Letting Hindley-Milner figure it out...",
  "Letting the compiler do the thinking...",
  "Letting the dough rise...",
  "Letting the logic breathe...",
  "Liberating the lambdas...",
  "Lifting a pure value into the effectful world...",
  "Lighting candles for the flaky tests...",
  "Lobbying the scheduler...",
  "Making friendship bracelets for the dependencies...",
  "Making illegal states unrepresentable...",
  "Making offerings to the CI...",
  "Manifesting solutions...",
  "Mapping over the possibilities...",
  "Massaging the heap...",
  "Maturing the methods...",
  "Mediating a dispute between spaces...",
  "Memoizing the vibes for later...",
  "Mesmerizing the memory banks...",
  "Mopping up spilled exceptions...",
  "Mountain climbing the modules...",
  "Naming the clouds in the distributed system...",
  "Negotiating with cosmic rays...",
  "Negotiating with deadlines...",
  "Negotiating with entropy...",
  "Nurturing the algorithm...",
  "Oiling the cogs...",
  "Organizing a potluck for the plugins...",
  "Origami-folding the configuration...",
  "Parasailing past the parameters...",
  "Pardoning the pointers...",
  "Passing notes between the containers...",
  "Pattern matching on the shape of reality...",
  "Performing arcane rituals...",
  "Petitioning the kernel...",
  "Petting the wild goroutines...",
  "Pickling the packages...",
  "Picnicking with the processes...",
  "Planting computational seeds...",
  "Plating the output nicely...",
  "Pleading with the logs...",
  "Poaching the pointers...",
  "Point-freeing until nothing remains but truth...",
  "Polishing the algorithms...",
  "Polishing the doorknobs of the API...",
  "Politely asking the CPU...",
  "Politely declining the null...",
  "Praying to the uptime gods...",
  "Preferring total functions to partial excuses...",
  "Presenting with pizzazz...",
  "Preserving referential transparency at all costs...",
  "Preserving the protocols...",
  "Proofing the promises...",
  "Proving it correct by construction...",
  "Pruning the decision branches...",
  "Purifying the parameters...",
  "Raising the exceptions...",
  "Reading bedtime stories to the daemons...",
  "Reading tea leaves...",
  "Reading the room...",
  "Rearranging deck chairs...",
  "Reasoning with the memory...",
  "Receiving transmissions from the cloud...",
  "Recursing until the base case shows mercy...",
  "Redeeming the recursion...",
  "Reducing the problem to its essence...",
  "Refusing to mutate on principle...",
  "Releasing the references...",
  "Reminding the retry loop that patience is a virtue...",
  "Reticulating splines...",
  "Reversing the polarity...",
  "Ringing a tiny bell for each resolved TODO...",
  "Ripening the results...",
  "Roasting the race conditions...",
  "Rolling out the runtime...",
  "Sacrificing to the demo gods...",
  "Sanctifying the source code...",
  "Sautéing the syntax errors...",
  "Scheduling a 1:1 with the garbage collector...",
  "Schmoozing the network...",
  "Scratching the ears of the event bus...",
  "Scrying the codebase...",
  "Scuba diving in the data...",
  "Searing the segments...",
  "Seasoning the solutions...",
  "Seducing the semicolons...",
  "Sending thoughts and prayers to prod...",
  "Serenading the syntax...",
  "Shaking loose the cobwebs...",
  "Shaking the magic 8-ball...",
  "Showing the queue how to wait its turn...",
  "Shuffling bits around...",
  "Skateboarding down the stack trace...",
  "Skydiving through the source...",
  "Slop forking open source...",
  "Smoking the subroutines...",
  "Snorkeling through the streams...",
  "Snowboarding through the schemas...",
  "Solving the riddles of RAM...",
  "Sorting the sock drawer of side effects...",
  "Spellbinding the stack frames...",
  "Spelunking through the stack...",
  "Spicing up the specs...",
  "Spinning up the squirrels...",
  "Sprinkling some magic dust...",
  "Squinting at the problem...",
  "Staring into the abyss...",
  "Starting a book club for the design docs...",
  "Stoking the furnace...",
  "Stroking chin thoughtfully...",
  "Summoning an algebraic data type from the void...",
  "Summoning semicolons...",
  "Surfing the syntax waves...",
  "Sweet-talking the API...",
  "Taking the bytes out for lunch...",
  "Taming wild pointers...",
  "Tangoing with type errors...",
  "Teaching electrons new tricks...",
  "Teaching old code new tricks...",
  "Teaching the cache to fetch...",
  "Telling the infinite loop a bedtime story...",
  "Thunking about it carefully...",
  "Tickling the stack...",
  "Topping with tests...",
  "Trading runtime errors for compile-time vibes...",
  "Transcending mere computation...",
  "Traversing the structure with good intentions...",
  "Trekking through the trees...",
  "Trusting the tail call to do the right thing...",
  "Tucking the threads in for a nap...",
  "Tuning the vibrations...",
  "Unbinding the variables...",
  "Unearthing buried bugs...",
  "Unlocking the secrets of silicon...",
  "Unraveling the regex...",
  "Untangling spaghetti...",
  "Untying the type knots...",
  "Vacuuming under the couch of edge cases...",
  "Waiting for a sign...",
  "Walking the race conditions on a leash...",
  "Waltzing through the codebase...",
  "Warming up the hamsters...",
  "Watering the houseplant of hope...",
  "Watering the logic tree...",
  "Waxing philosophical...",
  "Whisking the widgets...",
  "Whispering passwords to the void...",
  "Whispering sweet nothings to the compiler...",
  "Whispering to the bits...",
  "Willing it into existence...",
  "Winding up the clockwork...",
  "Wining and dining the servers...",
  "Wooing the while loops...",
  "Writing a strongly worded letter to latency...",
  "Zippering two infinite lists together carefully...",
];

function pickRandom(): string {
  return messages[Math.floor(Math.random() * messages.length)];
}

export default function (pi: ExtensionAPI) {
  pi.on("turn_start", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(pickRandom());
  });

  pi.on("turn_end", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(); // Reset for next time
  });
}
