#!/usr/bin/env bash
# until_fail [...command]
# runs command 10000 times until it fails

for i in {1..10000}; do
  echo "Attempt $i"
  "$@"
  exitCode=$?
  if [ "$exitCode" == 0 ]; then
    echo "Succeeded on attempt $i"
    exit $exitCode
  fi
done
