[bootstrap.brew.taps]

[bootstrap.packages]
# "brew:mas" = "latest"
# "mas:1586435171" = "latest" # Actions for Shortcuts
# "mas:497799835" = "latest"  # Xcode
# "mas:6465250302" = "latest" # AI Actions for Shortcuts
# "mas:899247664" = "latest"  # TestFlight
# "mas:1136220934" = "latest" # Infuse

[tools]
"aqua:smol-machines/smolvm" = "latest"
"aqua:wader/fq" = "latest"
"cargo:cargo-clean-all" = "latest"
"cargo:hurlfmt" = "latest"
"cargo:oha" = "latest"
"cargo:rustdoc-text" = "latest"
"github:blacktop/ipsw" = { version = "latest", asset_pattern = "ipsw_*_macOS_arm64_extras.tar.gz" }
"github:lexiforest/curl-impersonate" = "latest"
"go:github.com/orlangure/gocovsh" = "latest"
"go:github.com/ramonvermeulen/whosthere" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:portless" = "latest"
"npm:sfw" = "latest"
bun = "latest"
deno = "latest"
elixir = "latest"
erlang = "latest"
fnox = "latest"
gcloud = "latest"
go = "latest"
hk = "latest"
node = "latest"
pitchfork = "latest"
pkl = "latest"
pnpm = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
uv = "latest"
watchexec = "latest"
zig = "latest"
zls = "latest"

[settings]
idiomatic_version_file_enable_tools = ["rust"]
minimum_release_age = "24h"
experimental = true

[settings.status]
show_tools = true
show_env = true

[settings.python]
uv_venv_auto = true

[settings.npm]
package_manager = "pnpm"

[settings.ruby]
compile = false

[settings.github]
use_git_credentials = true
