[bootstrap.mise_shell_activate]

[bootstrap.brew.taps]

[bootstrap.packages]

[tools]
"aqua:smol-machines/smolvm" = "latest"
"cargo:cargo-clean-all" = "latest"
"cargo:hurlfmt" = "latest"
"cargo:oha" = "latest"
"cargo:rustdoc-text" = "latest"
"github:lexiforest/curl-impersonate" = { version = "latest", prerelease = true }
"go:golang.org/x/tools/gopls" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:hunkdiff" = "latest"
"npm:portless" = "latest"
"npm:sfw" = "latest"
bun = "latest"
deno = "latest"
duckdb = "latest"
elixir = "latest"
erlang = "latest"
fnox = "latest"
gcloud = "latest"
go = "latest"
helm = "latest"
hk = "latest"
jless = "latest"
k9s = "latest"
node = "latest"
pitchfork = "latest"
pkl = "latest"
pnpm = "latest"
pulumi = "latest"
python = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
shellcheck = "latest"
sops = "latest"
sqlc = "latest"
tokei = "latest"
tree-sitter = "latest"
trufflehog = "latest"
uv = "latest"
watchexec = "latest"
zig = "latest"
zizmor = "latest"
zls = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["rust"]
minimum_release_age = "12h"
experimental = true

[settings.status]
show_tools = true
show_env = true

[settings.python]
uv_venv_auto = true

[settings.npm]
package_manager = "pnpm"

[settings.ruby]
compile = false
